#!/bin/bash

SCRIPT_DIR=$(dirname $(realpath $0))
source ${SCRIPT_DIR}/XX-environment/base-variables


# container build files
rsync ${RSYNC_FLAGS} --delete --exclude=/backup \
	${DIR_HOMEDATA}/Documents/development/containers/ \
	/mnt/array/homeBraunJan/Documents/development/containers/

# development directories (Studium)
rsync ${RSYNC_FLAGS} --delete \
	--include-from="${RSYNC_PATTERN_DIR}/git-Studium" \
	${DIR_HOMEDATA}/Documents/development/git/Studium/ \
	/mnt/array/homeBraunJan/Documents/development/git/Studium/
